### PR TITLE
fix: escape `< >` symbols

### LINKED ISSUE #365: Output contain valid XML tags
##### Context
I'm testing out templates for integrating an AsyncAPI spec into a [Docusaurus](https://docusaurus.io) website. Docusaurus uses MDX which allows integrating JSX components and code into Markdown documents. I assume it accepts XML tags as HTML/JSX components which other Markdown parsers might ignore and render as text.

##### Actual issue
The output contains elements like `array<integer>` that can look like unclosed HTML elements to some parsers.

#### How to Reproduce

Write an AsyncAPI schema that include a property like:
```yaml
type: object
properties:
  prop1:
    type: object
    properties:
      prop2:
        type: array
        items:
            type: number
``` 

The generated document will contain a table with this:
```
... | array<number> | ...
```

#### Expected behavior

The line above should be formatted as code:
```
... | `array<number>` | ...
```

There should be no `<` and `>` in the generated document that isn't formatted as code or escaped appropriately.

### PR DESCRIPTION
**Pull request by korifey91**
**Description**

In order to allow different tools to correctly show `array`|`tuple` types of properties in schema we need to escape special symbols - `<`, `>`.

**Related issue(s)**
Fixes #365

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
that was fast

I think escaping work with one slash, not 2, cause then you see of of the slashes in rendered markdown

```
| Name | Type | Description | Value | Constraints | Notes |
|---|---|---|---|---|---|
| (root) | array\\<string\\> | - | - | [ 1 .. 5 ] unique items | - |
```

renders below
Screenshot 2024-04-18 at 12 16 16

why not choosing to simply add code block as the person that reported the issue wanted, so

```
| Name | Type | Description | Value | Constraints | Notes |
|---|---|---|---|---|---|
| (root) | `array<string>` | - | - | [ 1 .. 5 ] unique items | - |
```

that renders event better

Screenshot 2024-04-18 at 12 17 27


or
```
| Name | Type | Description | Value | Constraints | Notes |
|---|---|---|---|---|---|
| (root) | array&lt;string&gt; | - | - | [ 1 .. 5 ] unique items | - |
```

that also works

Screenshot 2024-04-18 at 12 18 41

**Comment by korifey91** [comment]
> that was fast
> 
> I think escaping work with one slash, not 2, cause then you see of of the slashes in rendered markdown
> 
> ```
> | Name | Type | Description | Value | Constraints | Notes |
> |---|---|---|---|---|---|
> | (root) | array\\<string\\> | - | - | [ 1 .. 5 ] unique items | - |
> ```
> 
> renders below Screenshot 2024-04-18 at 12 16 16
> 
> why not choosing to simply add code block as the person that reported the issue wanted, so
> 
> ```
> | Name | Type | Description | Value | Constraints | Notes |
> |---|---|---|---|---|---|
> | (root) | `array<string>` | - | - | [ 1 .. 5 ] unique items | - |
> ```
> 
> that renders event better
> 
> Screenshot 2024-04-18 at 12 17 27
> 
> or
> 
> ```
> | Name | Type | Description | Value | Constraints | Notes |
> |---|---|---|---|---|---|
> | (root) | array&lt;string&gt; | - | - | [ 1 .. 5 ] unique items | - |
> ```
> 
> that also works
> 
> Screenshot 2024-04-18 at 12 18 41

I think codeblocks is not the best choice, because we will have different visual formatting for types and lose consistency.

But `&lt;` and `&gt;` seems a good fit. 

P.S. It seems me IDE problem. I tryied to use one escape, but md looked wrong(like I change nothing).

**Comment by korifey91** [comment]
> that was fast
> 
> I think escaping work with one slash, not 2, cause then you see of of the slashes in rendered markdown
> 
> ```
> | Name | Type | Description | Value | Constraints | Notes |
> |---|---|---|---|---|---|
> | (root) | array\\<string\\> | - | - | [ 1 .. 5 ] unique items | - |
> ```
> 
> renders below Screenshot 2024-04-18 at 12 16 16
> 
> why not choosing to simply add code block as the person that reported the issue wanted, so
> 
> ```
> | Name | Type | Description | Value | Constraints | Notes |
> |---|---|---|---|---|---|
> | (root) | `array<string>` | - | - | [ 1 .. 5 ] unique items | - |
> ```
> 
> that renders event better
> 
> Screenshot 2024-04-18 at 12 17 27
> 
> or
> 
> ```
> | Name | Type | Description | Value | Constraints | Notes |
> |---|---|---|---|---|---|
> | (root) | array&lt;string&gt; | - | - | [ 1 .. 5 ] unique items | - |
> ```
> 
> that also works
> 
> Screenshot 2024-04-18 at 12 18 41

I think codeblocks is not the best choice, because we will have different visual formatting for types and lose consistency.

But `&lt;` and `&gt;` seems a good fit. 

P.S. It seems me IDE problem. I tryied to use one escape, but md looked wrong(like I change nothing).

**Comment by derberg** [comment]
ok, then lets be on the safe side and use what works, which is `&lt;` and `&gt;`

**Comment by korifey91** [comment]
@derberg Could you take a look again?

**Review by derberg — APPROVED** [review]
perfect work, thanks a 💯 !

**Pull request merged**
