### PR TITLE
feat: update to parser API v3

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR updates the parser API to v3 and removes messageId usage. It also fixes dependency shift.

**Related issue(s)**
Fixes https://github.com/asyncapi/markdown-template/issues/385
Blocked by https://github.com/asyncapi/generator/pull/1066 
Blocked by https://github.com/asyncapi/cli/pull/908

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
generator PR approved

you're getting some merge conflicts

**Comment by abhikt48** [comment]
@jonaslagoni Can we merge this PR as [asyncapi/cli/908](https://github.com/asyncapi/cli/pull/908) is merged now.

**Review by fmvilas — APPROVED** [review]

**Review by fmvilas — CHANGES_REQUESTED** [review]
Damn, you're getting some conflicts now and tests are failing 😅 Other than that, it's ready.

**Comment by jonaslagoni** [comment]
Ready to be reviewed for a final time @fmvilas @derberg

**Review by fmvilas — APPROVED** [review]

**Comment by jonaslagoni** [comment]
🤔 pretty sure this should have been a breaking change 🤔

**Pull request merged**
