### PR TITLE
feat!: render bindings, extensions and circular references

### LINKED ISSUE #195: `1.0.0` release - discussion
See @derberg 's comment -> https://github.com/asyncapi/markdown-template/pull/193#issuecomment-942283728

The template itself is stable and supports almost all things of AsyncAPI 2.0.0 (including 2.1.0 and 2.2.0) - the question is: Should we go with `1.0.0` version? As far as we know, a lot of people are using template in production and it's not causing too much trouble.

cc @derberg @fmvilas

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

- Render bindings for `server`, `channel`, `operation`, `message`
- Render extensions for `server`, `channel`, `operation`, `message`
- Change rendering of tags to markdown table (from list)
- Handle circular references in schemas
- Add unit tests

Examples:

##### Specification tags

| Name | Description | Documentation |
|---|---|---|
| root-tag1 | - | [External docs description 1](https://www.asyncapi.com/) |
| root-tag2 | Description 2 | [Find more info here](https://www.asyncapi.com/) |
| root-tag3 | - | - |
| root-tag4 | Description 4 | - |
| root-tag5 | - | [Find more info here](https://www.asyncapi.com/) |

#### `mqtt` Server specific information

| Name | Type | Description | Value | Constraints | Notes |
|---|---|---|---|---|---|
| clientId | - | - | `"guest"` | - | - |
| cleanSession | - | - | `"false"` | - | - |
| keepAlive | - | - | `"60"` | - | - |
| bindingVersion | - | - | `"0.1.0"` | - | - |
| lastWill | - | - | - | - | - |
| lastWill.topic | - | - | `"smartylighting/streetlights/1/0/lastwill"` | - | - |
| lastWill.qos | - | - | `"1"` | - | - |
| lastWill.message | - | - | `"so long and thanks for all the fish"` | - | - |
| lastWill.retain | - | - | `"false"` | - | - |

#### `mqtt` Operation specific information

| Name | Type | Description | Value | Constraints | Notes |
|---|---|---|---|---|---|
| qos | - | - | `"1"` | - | - |
| bindingVersion | - | - | `"0.1.0"` | - | - |

#### `http` Operation specific information

| Name | Type | Description | Value | Constraints | Notes |
|---|---|---|---|---|---|
| type | - | - | `"request"` | - | - |
| method | - | - | `"GET"` | - | - |
| query | object | - | - | - | **additional properties are NOT allowed** |
| query.companyId | number | The Id of the company. | - | >= 1 | **required** |

#### `kafka` Operation specific information

| Name | Type | Description | Value | Constraints | Notes |
|---|---|---|---|---|---|
| clientId | - | - | `"my-app-id"` | - | - |

#### Channel Extensions

| Name | Type | Description | Value | Constraints | Notes |
|---|---|---|---|---|---|
| x-security | - | - | - | - | - |
| x-security.tokenUrl | - | - | `"https://authserver.example/token"` | - | - |
| x-security.scopes | - | - | - | - | - |
| x-security.scopes.streetlights:on | - | - | `"Ability to switch lights on"` | - | - |
| x-security.scopes.streetlights:off | - | - | `"Ability to switch lights off"` | - | - |
| x-security.scopes.streetlights:dim | - | - | `"Ability to dim the lights"` | - | - |

**Related issue**
Resolves #195

### CODE REVIEW

**Review by derberg — DISMISSED** [review]
there is literally nothing I could ask you to fix in this PR. My only request is to add some screenshots to description to show how these look like when added so folks that check out details of the release see it without using the release

**Review by jonaslagoni — APPROVED** [review]
LGTM 👍

**Comment by magicmatatjahu** [comment]
@derberg I think that it's the good time to release `1.0.0` 😅

**Comment by derberg** [comment]
@magicmatatjahu 😄 can you update me on this one, what actually changed? as I cannot see any updates to the description 🤔

**Comment by magicmatatjahu** [comment]
@derberg Nothing has changed since October 😅  I just forgot about it - I remembered when I was collecting an update for all of December and mid-January from my area. What is in the description are changes in this PR, that is rendering of bindings, extensions, support for circular scheme etc :)

**Review by derberg — APPROVED** [review]
Update description so this PR closes https://github.com/asyncapi/markdown-template/issues/195 issue

Well done 👏🏼

**Pull request merged**
